sed -i 's/\(.\{6\}\)//' team-page001.txt &&
sed -i 's/\(.\{6\}\)//' team-page002.txt &&
sed -i 's/\(.\{6\}\)//' team-page003.txt &&
sed -i 's/\(.\{6\}\)//' team-page004.txt &&
sed -i 's/\(.\{6\}\)//' team-page005.txt &&
sed -i 's/\(.\{6\}\)//' team-page006.txt &&
sed -i 's/\(.\{6\}\)//' team-page007.txt &&
sed -i 's/\(.\{6\}\)//' team-page008.txt &&
sed -i 's/\(.\{6\}\)//' team-page009.txt &&
sed -i 's/\(.\{6\}\)//' team-page010.txt &&
sed -i 's/\(.\{6\}\)//' team-page011.txt &&
sed -i 's/\(.\{6\}\)//' team-page012.txt &&
sed -i 's/\(.\{6\}\)//' team-page013.txt &&
sed -i 's/\(.\{6\}\)//' team-page014.txt &&
sed -i 's/\(.\{6\}\)//' team-page015.txt &&
sed -i 's/\(.\{6\}\)//' team-page016.txt &&
sed -i 's/\(.\{6\}\)//' team-page017.txt &&
sed -i 's/\(.\{6\}\)//' team-page018.txt &&
sed -i 's/\(.\{6\}\)//' team-page019.txt &&
sed -i 's/\(.\{6\}\)//' team-page020.txt &&
sed -i 's/\(.\{6\}\)//' team-page021.txt &&
sed -i 's/\(.\{6\}\)//' team-page022.txt &&
sed -i 's/\(.\{6\}\)//' team-page023.txt &&
sed -i 's/\(.\{6\}\)//' team-page024.txt &&
sed -i 's/\(.\{6\}\)//' team-page025.txt &&
sed -i 's/\(.\{6\}\)//' team-page026.txt &&
sed -i 's/\(.\{6\}\)//' team-page027.txt &&
sed -i 's/\(.\{6\}\)//' team-page028.txt &&
sed -i 's/\(.\{6\}\)//' team-page029.txt &&
sed -i 's/\(.\{6\}\)//' team-page030.txt &&
sed -i 's/\(.\{6\}\)//' team-page031.txt &&
sed -i 's/\(.\{6\}\)//' team-page032.txt &&
sed -i 's/\(.\{6\}\)//' team-page033.txt &&
sed -i 's/\(.\{6\}\)//' team-page034.txt &&
sed -i 's/\(.\{6\}\)//' team-page035.txt &&
sed -i 's/\(.\{6\}\)//' team-page036.txt &&
sed -i 's/\(.\{6\}\)//' team-page037.txt &&
sed -i 's/\(.\{6\}\)//' team-page038.txt &&
sed -i 's/\(.\{6\}\)//' team-page039.txt &&
sed -i 's/\(.\{6\}\)//' team-page040.txt &&
sed -i 's/\(.\{6\}\)//' team-page041.txt &&
sed -i 's/\(.\{6\}\)//' team-page042.txt &&
sed -i 's/\(.\{6\}\)//' team-page043.txt &&
sed -i 's/\(.\{6\}\)//' team-page044.txt &&
sed -i 's/\(.\{6\}\)//' team-page045.txt &&
sed -i 's/\(.\{6\}\)//' team-page046.txt &&
sed -i 's/\(.\{6\}\)//' team-page047.txt &&
sed -i 's/\(.\{6\}\)//' team-page048.txt &&
sed -i 's/\(.\{6\}\)//' team-page049.txt &&
sed -i 's/\(.\{6\}\)//' team-page050.txt &&
sed -i 's/\(.\{6\}\)//' team-page051.txt &&
sed -i 's/\(.\{6\}\)//' team-page052.txt &&
sed -i 's/\(.\{6\}\)//' team-page053.txt &&
sed -i 's/\(.\{6\}\)//' team-page054.txt &&
sed -i 's/\(.\{6\}\)//' team-page055.txt &&
sed -i 's/\(.\{6\}\)//' team-page056.txt &&
sed -i 's/\(.\{6\}\)//' team-page057.txt &&
sed -i 's/\(.\{6\}\)//' team-page058.txt &&
sed -i 's/\(.\{6\}\)//' team-page059.txt &&
sed -i 's/\(.\{6\}\)//' team-page060.txt &&
sed -i 's/\(.\{6\}\)//' team-page061.txt &&
sed -i 's/\(.\{6\}\)//' team-page062.txt &&
sed -i 's/\(.\{6\}\)//' team-page063.txt &&
sed -i 's/\(.\{6\}\)//' team-page064.txt &&
sed -i 's/\(.\{6\}\)//' team-page065.txt &&
sed -i 's/\(.\{6\}\)//' team-page066.txt &&
sed -i 's/\(.\{6\}\)//' team-page067.txt &&
sed -i 's/\(.\{6\}\)//' team-page068.txt &&
sed -i 's/\(.\{6\}\)//' team-page069.txt &&
sed -i 's/\(.\{6\}\)//' team-page070.txt &&
sed -i 's/\(.\{6\}\)//' team-page071.txt &&
sed -i 's/\(.\{6\}\)//' team-page072.txt &&
sed -i 's/\(.\{6\}\)//' team-page073.txt &&
sed -i 's/\(.\{6\}\)//' team-page074.txt &&
sed -i 's/\(.\{6\}\)//' team-page075.txt &&
sed -i 's/\(.\{6\}\)//' team-page076.txt &&
sed -i 's/\(.\{6\}\)//' team-page077.txt &&
sed -i 's/\(.\{6\}\)//' team-page078.txt &&
sed -i 's/\(.\{6\}\)//' team-page079.txt &&
sed -i 's/\(.\{6\}\)//' team-page080.txt &&
sed -i 's/\(.\{6\}\)//' team-page081.txt &&
sed -i 's/\(.\{6\}\)//' team-page082.txt &&
sed -i 's/\(.\{6\}\)//' team-page083.txt &&
sed -i 's/\(.\{6\}\)//' team-page084.txt &&
sed -i 's/\(.\{6\}\)//' team-page085.txt &&
sed -i 's/\(.\{6\}\)//' team-page086.txt &&
sed -i 's/\(.\{6\}\)//' team-page087.txt &&
sed -i 's/\(.\{6\}\)//' team-page088.txt &&
sed -i 's/\(.\{6\}\)//' team-page089.txt &&
sed -i 's/\(.\{6\}\)//' team-page090.txt

